config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'events/create_event_a'
  get 'events/create_event_b'
  root 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user! 

  def create_event_a
    user_id = current_user.id
    IterableApiService.create_event_a(user_id)
    render json: { message: 'Event A created successfully' }
  end

  def create_event_b
    user_id = current_user.id
    event_created = IterableApiService.create_event_b(user_id)
    if event_created
      email_sent = IterableApiService.send_email_notification(user_id, 'EventB')
      if email_sent
        render json: { message: 'Event B created successfully and email notification sent' }
      else
        render json: { message: 'Event B created successfully but email notification failed' }
      end
    else
      render json: { message: 'Failed to create Event B' }, status: :unprocessable_entity
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def after_sign_in_path_for(resource)
    # Redirect to a custom path after login
    events_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/create_event_a.html.erb
<h1>Create Event A</h1>
<%= button_to 'Create Event A', events_create_event_a_path, method: :post %>

app/views/events/create_event_b.html.erb
<h1>Create Event B</h1>
<%= button_to 'Create Event B', events_create_event_b_path, method: :post %>

app/views/events/index.html.erb
<h1>Welcome <%= current_user.email %></h1>
<%= button_to 'Create Event A', events_create_event_a_path, method: :get %>
<%= button_to 'Create Event B', events_create_event_b_path, method: :get %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IterableIntegration</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>